{% set name = "sceptre-file-resolver" %}
{% set version = "1.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sceptre-file-resolver-{{ version }}.tar.gz
  sha256: 8c148653e723fb71d7a442ee2ff9ecb499f44b17fd1d7f7af3a2130f56b399f5

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=3
    - python {{ python_min }}
  run:
    - packaging ==16.8
    - python >={{ python_min }}
    - requests >=2.25,<3

test:
  imports:
    - resolver
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sceptre/sceptre-file-resolver
  summary: A Sceptre resolver to retrieve file content
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - admax18
    - mxr-conda
